---
# defaults file for rotorhazard
version: 3.1.0

tmp_dir: "/tmp"
target_dir: "/opt/RotorHazard"
work_dir: "{{target_dir}}/src/server/"
logs_dir: "{{work_dir}}/logs"

rh_user: rotorhazard
rh_group: rotorhazard

rh_service_name: rotorhazard

rh_config:
  GENERAL:
    HTTP_PORT: 5000
    ADMIN_USERNAME: admin
    ADMIN_PASSWORD: rotorhazard
    DEBUG: false
    CORS_ALLOWED_HOSTS: '*'
  HARDWARE:
    I2C_BUS: 1
  SENSORS: { }
  SERIAL_PORTS:
    - /dev/ttyS0
  LED:
    LED_COUNT: 35
    LED_ROWS: 5
    LED_PIN: 10
    LED_FREQ_HZ: 800000
    LED_DMA: 10
    LED_INVERT: false
    LED_CHANNEL: 0
    PANEL_ROTATE: 0
    INVERTED_PANEL_ROWS: false
  LOGGING:
    CONSOLE_LEVEL: INFO
    SYSLOG_LEVEL: NONE
    FILELOG_LEVEL: INFO
    FILELOG_NUM_KEEP: 30
    CONSOLE_STREAM: stdout
