---
- name: Create rtcsync systemd unit
  become: true
  template:
    src: "rtcsync_systemd.j2"
    dest: "/lib/systemd/system/rtcsync.service"
    force: true
    owner: root
    group: root
    mode: "0644"

- name: Start rtcsync service
  become: true
  systemd:
    name: 'rtcsync'
    state: restarted
    enabled: true
    daemon_reload: yes
