- name: Set static ip address on our wlan0 interface
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface wlan0
        static ip_address=192.168.4.1/24
        nohook wpa_supplicant

- name: Restart dhcpcd service
  become: true
  systemd:
    name: 'dhcpcd'
    state: restarted
    enabled: true
    daemon_reload: yes
